# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Industry.destroy_all

industry_data = [{name: 'Accounting', linkedin_code: '47'},
{name: 'Airlines/Aviation', linkedin_code: '94'},
{name: 'Alternative Dispute Resolution', linkedin_code: '120'},
{name: 'Alternative Medicine', linkedin_code: '125'},
{name: 'Animation', linkedin_code: '127'},
{name: 'Apparel & Fashion', linkedin_code: '19'},
{name: 'Architecture & Planning', linkedin_code: '50'},
{name: 'Arts & Crafts', linkedin_code: '111'},
{name: 'Automotive', linkedin_code: '53'},
{name: 'Aviation & Aerospace', linkedin_code: '52'},
{name: 'Banking', linkedin_code: '41'},
{name: 'Biotechnology', linkedin_code: '12'},
{name: 'Broadcast Media', linkedin_code: '36'},
{name: 'Building Materials', linkedin_code: '49'},
{name: 'Business Supplies & Equipment', linkedin_code: '138'},
{name: 'Capital Markets', linkedin_code: '129'},
{name: 'Chemicals', linkedin_code: '54'},
{name: 'Civic & Social Organization', linkedin_code: '90'},
{name: 'Civil Engineering', linkedin_code: '51'},
{name: 'Commercial Real Estate', linkedin_code: '128'},
{name: 'Computer & Network Security', linkedin_code: '118'},
{name: 'Computer Games', linkedin_code: '109'},
{name: 'Computer Hardware', linkedin_code: '3'},
{name: 'Computer Networking', linkedin_code: '5'},
{name: 'Computer Software', linkedin_code: '4'},
{name: 'Construction', linkedin_code: '48'},
{name: 'Consumer Electronics', linkedin_code: '24'},
{name: 'Consumer Goods', linkedin_code: '25'},
{name: 'Consumer Services', linkedin_code: '91'},
{name: 'Cosmetics', linkedin_code: '18'},
{name: 'Dairy', linkedin_code: '65'},
{name: 'Defense & Space', linkedin_code: '1'},
{name: 'Design', linkedin_code: '99'},
{name: 'Education Management', linkedin_code: '69'},
{name: 'E-Learning', linkedin_code: '132'},
{name: 'Electrical/Electronic Manufacturing', linkedin_code: '112'},
{name: 'Entertainment', linkedin_code: '28'},
{name: 'Environmental Services', linkedin_code: '86'},
{name: 'Events Services', linkedin_code: '110'},
{name: 'Executive Office', linkedin_code: '76'},
{name: 'Facilities Services', linkedin_code: '122'},
{name: 'Farming', linkedin_code: '63'},
{name: 'Financial Services', linkedin_code: '43'},
{name: 'Fine Art', linkedin_code: '38'},
{name: 'Fishery', linkedin_code: '66'},
{name: 'Food & Beverages', linkedin_code: '34'},
{name: 'Food Production', linkedin_code: '23'},
{name: 'Fund-Raising', linkedin_code: '101'},
{name: 'Furniture', linkedin_code: '26'},
{name: 'Gambling & Casinos', linkedin_code: '29'},
{name: 'Glass, Ceramics & Concrete', linkedin_code: '145'},
{name: 'Government Administration', linkedin_code: '75'},
{name: 'Government Relations', linkedin_code: '148'},
{name: 'Graphic Design', linkedin_code: '140'},
{name: 'Health, Wellness & Fitness', linkedin_code: '124'},
{name: 'Higher Education', linkedin_code: '68'},
{name: 'Hospital & Health Care', linkedin_code: '14'},
{name: 'Hospitality', linkedin_code: '31'},
{name: 'Human Resources', linkedin_code: '137'},
{name: 'Import & Export', linkedin_code: '134'},
{name: 'Individual & Family Services', linkedin_code: '88'},
{name: 'Industrial Automation', linkedin_code: '147'},
{name: 'Information Services', linkedin_code: '84'},
{name: 'Information Technology & Services', linkedin_code: '96'},
{name: 'Insurance', linkedin_code: '42'},
{name: 'International Affairs', linkedin_code: '74'},
{name: 'International Trade & Development', linkedin_code: '141'},
{name: 'Internet', linkedin_code: '6'},
{name: 'Investment Banking', linkedin_code: '45'},
{name: 'Investment Management', linkedin_code: '46'},
{name: 'Judiciary', linkedin_code: '73'},
{name: 'Law Enforcement', linkedin_code: '77'},
{name: 'Law Practice', linkedin_code: '9'},
{name: 'Legal Services', linkedin_code: '10'},
{name: 'Legislative Office', linkedin_code: '72'},
{name: 'Leisure, Travel & Tourism', linkedin_code: '30'},
{name: 'Libraries', linkedin_code: '85'},
{name: 'Logistics & Supply Chain', linkedin_code: '116'},
{name: 'Luxury Goods & Jewelry', linkedin_code: '143'},
{name: 'Machinery', linkedin_code: '55'},
{name: 'Management Consulting', linkedin_code: '11'},
{name: 'Maritime', linkedin_code: '95'},
{name: 'Market Research', linkedin_code: '97'},
{name: 'Marketing & Advertising', linkedin_code: '80'},
{name: 'Mechanical or Industrial Engineering', linkedin_code: '135'},
{name: 'Media Production', linkedin_code: '126'},
{name: 'Medical Devices', linkedin_code: '17'},
{name: 'Medical Practice', linkedin_code: '13'},
{name: 'Mental Health Care', linkedin_code: '139'},
{name: 'Military', linkedin_code: '71'},
{name: 'Mining & Metals', linkedin_code: '56'},
{name: 'Motion Pictures & Film', linkedin_code: '35'},
{name: 'Museums & Institutions', linkedin_code: '37'},
{name: 'Music', linkedin_code: '115'},
{name: 'Nanotechnology', linkedin_code: '114'},
{name: 'Newspapers', linkedin_code: '81'},
{name: 'Non-Profit Organization Management', linkedin_code: '100'},
{name: 'Oil & Energy', linkedin_code: '57'},
{name: 'Online Media', linkedin_code: '113'},
{name: 'Outsourcing/Offshoring', linkedin_code: '123'},
{name: 'Package/Freight Delivery', linkedin_code: '87'},
{name: 'Packaging & Containers', linkedin_code: '146'},
{name: 'Paper & Forest Products', linkedin_code: '61'},
{name: 'Performing Arts', linkedin_code: '39'},
{name: 'Pharmaceuticals', linkedin_code: '15'},
{name: 'Philanthropy', linkedin_code: '131'},
{name: 'Photography', linkedin_code: '136'},
{name: 'Plastics', linkedin_code: '117'},
{name: 'Political Organization', linkedin_code: '107'},
{name: 'Primary/Secondary Education', linkedin_code: '67'},
{name: 'Printing', linkedin_code: '83'},
{name: 'Professional Training & Coaching', linkedin_code: '105'},
{name: 'Program Development', linkedin_code: '102'},
{name: 'Public Policy', linkedin_code: '79'},
{name: 'Public Relations & Communications', linkedin_code: '98'},
{name: 'Public Safety', linkedin_code: '78'},
{name: 'Publishing', linkedin_code: '82'},
{name: 'Railroad Manufacture', linkedin_code: '62'},
{name: 'Ranching', linkedin_code: '64'},
{name: 'Real Estate', linkedin_code: '44'},
{name: 'Recreational Facilities & Services', linkedin_code: '40'},
{name: 'Religious Institutions', linkedin_code: '89'},
{name: 'Renewables & Environment', linkedin_code: '144'},
{name: 'Research', linkedin_code: '70'},
{name: 'Restaurants', linkedin_code: '32'},
{name: 'Retail', linkedin_code: '27'},
{name: 'Security & Investigations', linkedin_code: '121'},
{name: 'Semiconductors', linkedin_code: '7'},
{name: 'Shipbuilding', linkedin_code: '58'},
{name: 'Sporting Goods', linkedin_code: '20'},
{name: 'Sports', linkedin_code: '33'},
{name: 'Staffing & Recruiting', linkedin_code: '104'},
{name: 'Supermarkets', linkedin_code: '22'},
{name: 'Telecommunications', linkedin_code: '8'},
{name: 'Textiles', linkedin_code: '60'},
{name: 'Think Tanks', linkedin_code: '130'},
{name: 'Tobacco', linkedin_code: '21'},
{name: 'Translation & Localization', linkedin_code: '108'},
{name: 'Transportation/Trucking/Railroad', linkedin_code: '92'},
{name: 'Utilities', linkedin_code: '59'},
{name: 'Venture Capital & Private Equity', linkedin_code: '106'},
{name: 'Veterinary', linkedin_code: '16'},
{name: 'Warehousing', linkedin_code: '93'},
{name: 'Wholesale', linkedin_code: '133'},
{name: 'Wine & Spirits', linkedin_code: '142'},
{name: 'Wireless', linkedin_code: '119'},
{name: 'Writing & Editing', linkedin_code: '103'}]

industry_data.each {|ind| Industry.create!(ind)}


User.create!(admin: true, first_name: 'Admin', last_name: 'System', email: 'admin@gal.com', password: '123456', industry: Industry.first, state: 'registered')
